project:
  type: website
  output-dir: docs
resources:
  - images/

website:
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"
      - href: CV/index.qmd
        text: "Curr√≠culum Vitae"

format:
  html:
    theme: flatly  
    toc: false  
    number-sections: false
    toc-location: left  
